type: prometheus

status:
  class: exporter
  stability:
    beta: [metrics]
  distributions:
  - core
  - contrib
  codeowners:
    active: [Aneurysm9, dashpole, ArthurSens]

tests:
  config:
    endpoint: "127.0.0.1:1234"
  goleak:
    ignore:
      top:
        # See https://github.com/census-instrumentation/opencensus-go/issues/1191 for more information.
        - "go.opencensus.io/stats/view.(*worker).start"

telemetry:
  metrics:
    otelcol_exporter_refused_metric_points:
      enabled: true
      description: Number of metric points refused by the prometheus exporter.
      unit: "{datapoints}"
      sum:
        value_type: int
        monotonic: true